{"uuid": "2ac500c4-2ca7-45e4-852f-5ad76a873ac0", "children": ["e308f08d-209a-4e95-b7fa-61d6e3eb7a32", "9df09b14-5ff0-4246-85d8-03db019eb043", "72954d30-221d-46f3-bc0d-83d5bd380113"], "befores": [{"name": "_xunit_setup_class_fixture_TestDept", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 845, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 767, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\code\\InterAutoTest\\testcase\\test_dept.py\", line 31, in setup_class\n    \"password\": \"123456\"\n  File \"E:\\code\\InterAutoTest\\common\\tokenUtill.py\", line 5, in getToken\n    return res[\"data\"][\"token\"]\n"}, "start": 1653983414511, "stop": 1653983415534}], "start": 1653983414511, "stop": 1653983416258}